<?php

/**
 * Implements hook_preprocess().
 */
function site_map_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $map = t('There was an error by generating map.');
  $i = 0;
  if($paragraph->bundle() == 'map') {

    if ($paragraph->hasField('field_map_adresse')) {
      $address = $paragraph->get('field_map_adresse')->getValue();
      if (!empty($address[0]['value'])) {
        $address = explode(PHP_EOL, $address[0]['value']);
        array_walk($address, function(&$v){
          $v = trim($v);
        });
        $variables['address'] = implode(', ', $address);
        $i+=1;
      }
    }

    if ($paragraph->hasField('field_map_api_key')) {
      $api_key = $paragraph->get('field_map_api_key')->getValue();
      if (!empty($api_key[0]['value'])) {
        $variables['api_key'] = $api_key[0]['value'];
        $i+=1;
      }
    }

    if ($i == 2) {
      $map='<script type="text/javascript">
          var map;
          var geocoder;
          var loc = [];
          var styles = [
              {
                  "featureType": "administrative",
                  "elementType": "all",
                  "stylers": [
                      {
                          "visibility": "on"
                      },
                      {
                          "saturation": -100
                      },
                      {
                          "lightness": 20
                      }
                  ]
              },
              {
                  "featureType": "landscape.man_made",
                  "elementType": "all",
                  "stylers": [
                      {
                          "visibility": "simplified"
                      },
                      {
                          "saturation": -60
                      },
                      {
                          "lightness": 10
                      }
                  ]
              },
              {
                  "featureType": "landscape.natural",
                  "elementType": "all",
                  "stylers": [
                      {
                          "visibility": "simplified"
                      },
                      {
                          "saturation": -60
                      },
                      {
                          "lightness": 60
                      }
                  ]
              },
              {
                  "featureType": "poi",
                  "elementType": "geometry",
                  "stylers": [
                      {
                          "visibility": "on"
                      },
                      {                         "color": "#fafafa"
                      }
                  ]
              },
              {
                  "featureType": "poi",
                  "elementType": "geometry.stroke",
                  "stylers": [
                      {
                          "visibility": "on"
                      },
                      {
                          "color": "#dcdcdc"
                      }
                  ]
              },
              {
                  "featureType": "poi",
                  "elementType": "labels.text.fill",
                  "stylers": [
                      {
                          "color": "#5f82e3"
                      }
                  ]
              },
              {
                  "featureType": "poi",
                  "elementType": "labels.icon",
                  "stylers": [
                      {
                          "color": "#5f82e3"
                      },
                      {
                          "visibility": "on"
                      }
                  ]
              },
              {
                  "featureType": "road",
                  "elementType": "all",
                  "stylers": [
                      {
                          "visibility": "on"
                      },
                      {
                          "saturation": -100
                      },
                      {
                          "lightness": 40
                      }
                  ]
              },
              {
                  "featureType": "road.highway",
                  "elementType": "geometry.fill",
                  "stylers": [
                      {
                          "color": "#5f82e3"
                      }
                  ]
              },
              {
                  "featureType": "road.highway",
                  "elementType": "geometry.stroke",
                  "stylers": [
                      {
                          "color": "#3e5eb5"
                      }
                  ]
              },
              {
                  "featureType": "transit",
                  "elementType": "all",
                  "stylers": [
                      {
                          "visibility": "off"
                      },
                      {
                          "saturation": -100
                      },
                      {
                          "lightness": 60
                      }
                  ]
              },
              {
                  "featureType": "water",
                  "elementType": "all",
                  "stylers": [
                      {
                          "visibility": "on"
                      },
                      {
                          "saturation": -10
                      },
                      {
                          "lightness": 30
                      }
                  ]
              }
          ];

          function getAddress() {
            geocoder = new google.maps.Geocoder();
            geocoder.geocode({
                "address": "'.$variables['address'].'"
                }, function(results, status) {
                if (status === google.maps.GeocoderStatus.OK) {
                  loc.push(results[0].geometry.location.lat());
                  loc.push(results[0].geometry.location.lng());
                  var center = new google.maps.LatLng(results[0].geometry.location.lat(),results[0].geometry.location.lng());
                  map.panTo(center);
                }
            });
          }

          function initMap() {
            var mapLayer = document.getElementById("map-layer");
            var centerCoordinates = new google.maps.LatLng(51.5167,9.9167);
            var latlng = getAddress();
            //var defaultOptions = { center: centerCoordinates, zoom: 5 }
            var styledMap = new google.maps.StyledMapType(styles,
              {name: "Styled Map"});
            var mapOptions = {
              zoom: 12,
              center: centerCoordinates,
              scrollwheel: false, // disableScrollingWithMouseWheel as default
              disableDefaultUI: false,
              scaleControl: false,  // fixed to BOTTOM_RIGHT
              panControl: false,
              zoomControl: true,
              mapTypeControl: false,
              streetViewControl: true,
              streetViewControlOptions: {
            position: google.maps.ControlPosition.LEFT_BOTTOM
              },
              overviewMapControl: true,
            };

            map = new google.maps.Map(mapLayer, mapOptions);
            map.mapTypes.set("map_style", styledMap);
            map.setMapTypeId("map_style");
            geocoder = new google.maps.Geocoder();


                     Geocode("'.$variables['address'].'");

                      function Geocode(address,id) {
                      geocoder.geocode({
                      "address": address
                      }, function(results, status) {
                      if (status === google.maps.GeocoderStatus.OK) {
                      var result = results[0].geometry.location;
                      var icon = {
                          url: "/themes/custom/vanity/images/Standort_Pin.png",
                          scaledSize: new google.maps.Size(60, 80),
                      };
                      var marker = new google.maps.Marker({
                      position: result,
                      map: map,
                      title: address,
                      icon: icon,
                      url: ""
                      });

                      google.maps.event.addListener(marker, "click", function () {
                      window.location.href = this.url;
                      });
                      } else if (status === google.maps.GeocoderStatus.OVER_QUERY_LIMIT) {
                      setTimeout(function() {
                      Geocode(address,id);
                      }, 200);
                      } else {
                      alert("Geocode was not successful for the following reason:"
                      + status);
                      }
                      });
                      }

        }
        </script>
        <script	src="https://maps.googleapis.com/maps/api/js?key=' . $variables['api_key'] . '&callback=initMap" async defer></script>';

      echo $map;
    }

  }

}
